"""Smoke tests for src/pact/wavefront.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_wavefront():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.wavefront")
    assert mod is not None
