"""Smoke tests for src/pact/register.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_register():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.register")
    assert mod is not None

def test_assess_register_consistency_is_callable():
    """Function assess_register_consistency exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.register")
    fn = getattr(mod, "assess_register_consistency", None)
    assert fn is not None, "'assess_register_consistency' not found in pact.register"
    assert callable(fn)

def test_check_artifacts_for_drift_is_callable():
    """Function check_artifacts_for_drift exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.register")
    fn = getattr(mod, "check_artifacts_for_drift", None)
    assert fn is not None, "'check_artifacts_for_drift' not found in pact.register"
    assert callable(fn)
