"""Smoke tests for src/pact/events.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_events():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.events")
    assert mod is not None
