"""Smoke tests for src/pact/signals.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_signals():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.signals")
    assert mod is not None

def test_extract_log_key_is_callable():
    """Function extract_log_key exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.signals")
    fn = getattr(mod, "extract_log_key", None)
    assert fn is not None, "'extract_log_key' not found in src.pact.signals"
    assert callable(fn)

def test_fingerprint_signal_is_callable():
    """Function fingerprint_signal exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.signals")
    fn = getattr(mod, "fingerprint_signal", None)
    assert fn is not None, "'fingerprint_signal' not found in src.pact.signals"
    assert callable(fn)

def test_match_signal_to_project_is_callable():
    """Function match_signal_to_project exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.signals")
    fn = getattr(mod, "match_signal_to_project", None)
    assert fn is not None, "'match_signal_to_project' not found in src.pact.signals"
    assert callable(fn)
