"""Smoke tests for src/pact/auditor.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_auditor():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.auditor")
    assert mod is not None

def test_audit_spec_compliance_is_callable():
    """Function audit_spec_compliance exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.auditor")
    fn = getattr(mod, "audit_spec_compliance", None)
    assert fn is not None, "'audit_spec_compliance' not found in src.pact.auditor"
    assert callable(fn)

def test_render_audit_markdown_is_callable():
    """Function render_audit_markdown exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.auditor")
    fn = getattr(mod, "render_audit_markdown", None)
    assert fn is not None, "'render_audit_markdown' not found in src.pact.auditor"
    assert callable(fn)
