"""Smoke tests for src/pact/wizard.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_wizard():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    assert mod is not None

def test_build_wizard_questions_is_callable():
    """Function build_wizard_questions exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "build_wizard_questions", None)
    assert fn is not None, "'build_wizard_questions' not found in src.pact.wizard"
    assert callable(fn)

def test_run_wizard_interactive_is_callable():
    """Function run_wizard_interactive exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "run_wizard_interactive", None)
    assert fn is not None, "'run_wizard_interactive' not found in src.pact.wizard"
    assert callable(fn)

def test_answers_to_config_is_callable():
    """Function answers_to_config exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "answers_to_config", None)
    assert fn is not None, "'answers_to_config' not found in src.pact.wizard"
    assert callable(fn)

def test_resolve_test_framework_is_callable():
    """Function resolve_test_framework exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "resolve_test_framework", None)
    assert fn is not None, "'resolve_test_framework' not found in src.pact.wizard"
    assert callable(fn)

def test_generate_task_md_is_callable():
    """Function generate_task_md exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "generate_task_md", None)
    assert fn is not None, "'generate_task_md' not found in src.pact.wizard"
    assert callable(fn)

def test_generate_sops_md_is_callable():
    """Function generate_sops_md exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "generate_sops_md", None)
    assert fn is not None, "'generate_sops_md' not found in src.pact.wizard"
    assert callable(fn)

def test_generate_pact_yaml_is_callable():
    """Function generate_pact_yaml exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "generate_pact_yaml", None)
    assert fn is not None, "'generate_pact_yaml' not found in src.pact.wizard"
    assert callable(fn)

def test_load_wizard_config_from_file_is_callable():
    """Function load_wizard_config_from_file exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.wizard")
    fn = getattr(mod, "load_wizard_config_from_file", None)
    assert fn is not None, "'load_wizard_config_from_file' not found in src.pact.wizard"
    assert callable(fn)
