"""Smoke tests for src/pact/pitch_utils.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_pitch_utils():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.pitch_utils")
    assert mod is not None

def test_extract_pitch_summary_is_callable():
    """Function extract_pitch_summary exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.pitch_utils")
    fn = getattr(mod, "extract_pitch_summary", None)
    assert fn is not None, "'extract_pitch_summary' not found in pact.pitch_utils"
    assert callable(fn)

def test_format_pitch_summary_is_callable():
    """Function format_pitch_summary exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.pitch_utils")
    fn = getattr(mod, "format_pitch_summary", None)
    assert fn is not None, "'format_pitch_summary' not found in pact.pitch_utils"
    assert callable(fn)

def test_build_pitch_context_for_handoff_is_callable():
    """Function build_pitch_context_for_handoff exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.pitch_utils")
    fn = getattr(mod, "build_pitch_context_for_handoff", None)
    assert fn is not None, "'build_pitch_context_for_handoff' not found in pact.pitch_utils"
    assert callable(fn)
