"""Smoke tests for src/pact/mcp_server.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_mcp_server():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.mcp_server")
    assert mod is not None
