"""Smoke tests for src/pact/events.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_events():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.events")
    assert mod is not None
