"""Smoke tests for src/pact/schemas_tasks.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_schemas_tasks():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.schemas_tasks")
    assert mod is not None
