"""Smoke tests for src/pact/quality.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_quality():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.quality")
    assert mod is not None

def test_audit_contract_specificity_is_callable():
    """Function audit_contract_specificity exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.quality")
    fn = getattr(mod, "audit_contract_specificity", None)
    assert fn is not None, "'audit_contract_specificity' not found in src.pact.quality"
    assert callable(fn)
