"""Smoke tests for src/pact/agents/contract_author.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_agents_contract_author():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.agents.contract_author")
    assert mod is not None

def test_author_contract_is_callable():
    """Function author_contract exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.agents.contract_author")
    fn = getattr(mod, "author_contract", None)
    assert fn is not None, "'author_contract' not found in src.pact.agents.contract_author"
    assert callable(fn)
