"""Smoke tests for src/pact/retrospective.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_retrospective():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.retrospective")
    assert mod is not None

def test_generate_retrospective_is_callable():
    """Function generate_retrospective exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.retrospective")
    fn = getattr(mod, "generate_retrospective", None)
    assert fn is not None, "'generate_retrospective' not found in src.pact.retrospective"
    assert callable(fn)

def test_load_retrospective_is_callable():
    """Function load_retrospective exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.retrospective")
    fn = getattr(mod, "load_retrospective", None)
    assert fn is not None, "'load_retrospective' not found in src.pact.retrospective"
    assert callable(fn)

def test_load_all_retrospectives_is_callable():
    """Function load_all_retrospectives exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.retrospective")
    fn = getattr(mod, "load_all_retrospectives", None)
    assert fn is not None, "'load_all_retrospectives' not found in src.pact.retrospective"
    assert callable(fn)
