"""Smoke tests for src/pact/sentinel.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_sentinel():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.sentinel")
    assert mod is not None
