"""Smoke tests for src/pact/task_list.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_task_list():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.task_list")
    assert mod is not None

def test_generate_task_list_is_callable():
    """Function generate_task_list exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.task_list")
    fn = getattr(mod, "generate_task_list", None)
    assert fn is not None, "'generate_task_list' not found in src.pact.task_list"
    assert callable(fn)

def test_render_task_list_markdown_is_callable():
    """Function render_task_list_markdown exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.task_list")
    fn = getattr(mod, "render_task_list_markdown", None)
    assert fn is not None, "'render_task_list_markdown' not found in src.pact.task_list"
    assert callable(fn)

def test_update_task_status_is_callable():
    """Function update_task_status exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.task_list")
    fn = getattr(mod, "update_task_status", None)
    assert fn is not None, "'update_task_status' not found in src.pact.task_list"
    assert callable(fn)
