"""Smoke tests for src/pact/backends/openai.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_backends_openai():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.backends.openai")
    assert mod is not None
