"""Smoke tests for src/pact/incidents.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_incidents():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.incidents")
    assert mod is not None
