"""Smoke tests for src/pact/adopt.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_adopt():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.adopt")
    assert mod is not None

def test_generate_smoke_tests_is_callable():
    """Function generate_smoke_tests exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.adopt")
    fn = getattr(mod, "generate_smoke_tests", None)
    assert fn is not None, "'generate_smoke_tests' not found in src.pact.adopt"
    assert callable(fn)

def test_build_decomposition_tree_is_callable():
    """Function build_decomposition_tree exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.adopt")
    fn = getattr(mod, "build_decomposition_tree", None)
    assert fn is not None, "'build_decomposition_tree' not found in src.pact.adopt"
    assert callable(fn)

def test_link_existing_implementations_is_callable():
    """Function link_existing_implementations exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.adopt")
    fn = getattr(mod, "link_existing_implementations", None)
    assert fn is not None, "'link_existing_implementations' not found in src.pact.adopt"
    assert callable(fn)

def test_adopt_codebase_is_callable():
    """Function adopt_codebase exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.adopt")
    fn = getattr(mod, "adopt_codebase", None)
    assert fn is not None, "'adopt_codebase' not found in src.pact.adopt"
    assert callable(fn)
