"""Smoke tests for src/pact/schemas.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_schemas():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.schemas")
    assert mod is not None

def test_validate_answer_is_callable():
    """Function validate_answer exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.schemas")
    fn = getattr(mod, "validate_answer", None)
    assert fn is not None, "'validate_answer' not found in src.pact.schemas"
    assert callable(fn)
