"""Smoke tests for src/pact/incidents.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_incidents():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.incidents")
    assert mod is not None
