"""Smoke tests for src/pact/human/git.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_human_git():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.human.git")
    assert mod is not None
