"""Smoke tests for src/pact/interface_stub.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_interface_stub():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    assert mod is not None

def test_get_required_exports_is_callable():
    """Function get_required_exports exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "get_required_exports", None)
    assert fn is not None, "'get_required_exports' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_stub_is_callable():
    """Function render_stub exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_stub", None)
    assert fn is not None, "'render_stub' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_stub_ts_is_callable():
    """Function render_stub_ts exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_stub_ts", None)
    assert fn is not None, "'render_stub_ts' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_log_key_preamble_ts_is_callable():
    """Function render_log_key_preamble_ts exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_log_key_preamble_ts", None)
    assert fn is not None, "'render_log_key_preamble_ts' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_stub_js_is_callable():
    """Function render_stub_js exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_stub_js", None)
    assert fn is not None, "'render_stub_js' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_log_key_preamble_js_is_callable():
    """Function render_log_key_preamble_js exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_log_key_preamble_js", None)
    assert fn is not None, "'render_log_key_preamble_js' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_dependency_map_is_callable():
    """Function render_dependency_map exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_dependency_map", None)
    assert fn is not None, "'render_dependency_map' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_compact_deps_is_callable():
    """Function render_compact_deps exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_compact_deps", None)
    assert fn is not None, "'render_compact_deps' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_log_key_preamble_is_callable():
    """Function render_log_key_preamble exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_log_key_preamble", None)
    assert fn is not None, "'render_log_key_preamble' not found in src.pact.interface_stub"
    assert callable(fn)

def test_project_id_hash_is_callable():
    """Function project_id_hash exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "project_id_hash", None)
    assert fn is not None, "'project_id_hash' not found in src.pact.interface_stub"
    assert callable(fn)

def test_context_fence_is_callable():
    """Function context_fence exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "context_fence", None)
    assert fn is not None, "'context_fence' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_handoff_brief_is_callable():
    """Function render_handoff_brief exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_handoff_brief", None)
    assert fn is not None, "'render_handoff_brief' not found in src.pact.interface_stub"
    assert callable(fn)

def test_render_progress_snapshot_is_callable():
    """Function render_progress_snapshot exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "render_progress_snapshot", None)
    assert fn is not None, "'render_progress_snapshot' not found in src.pact.interface_stub"
    assert callable(fn)

def test_build_code_agent_context_is_callable():
    """Function build_code_agent_context exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.interface_stub")
    fn = getattr(mod, "build_code_agent_context", None)
    assert fn is not None, "'build_code_agent_context' not found in src.pact.interface_stub"
    assert callable(fn)
