"""Smoke tests for src/pact/agents/code_author.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_agents_code_author():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.agents.code_author")
    assert mod is not None

def test_author_code_is_callable():
    """Function author_code exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.agents.code_author")
    fn = getattr(mod, "author_code", None)
    assert fn is not None, "'author_code' not found in src.pact.agents.code_author"
    assert callable(fn)
