"""Smoke tests for src/pact/human/slack.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_human_slack():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.human.slack")
    assert mod is not None
