"""Smoke tests for src/pact/backends/anthropic.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_backends_anthropic():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.backends.anthropic")
    assert mod is not None
