"""Smoke tests for src/pact/drift.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_drift():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.drift")
    assert mod is not None

def test_capture_baseline_is_callable():
    """Function capture_baseline exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.drift")
    fn = getattr(mod, "capture_baseline", None)
    assert fn is not None, "'capture_baseline' not found in src.pact.drift"
    assert callable(fn)

def test_load_baseline_is_callable():
    """Function load_baseline exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.drift")
    fn = getattr(mod, "load_baseline", None)
    assert fn is not None, "'load_baseline' not found in src.pact.drift"
    assert callable(fn)

def test_detect_drift_is_callable():
    """Function detect_drift exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.drift")
    fn = getattr(mod, "detect_drift", None)
    assert fn is not None, "'detect_drift' not found in src.pact.drift"
    assert callable(fn)

def test_check_staleness_is_callable():
    """Function check_staleness exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.drift")
    fn = getattr(mod, "check_staleness", None)
    assert fn is not None, "'check_staleness' not found in src.pact.drift"
    assert callable(fn)
