"""Smoke tests for src/pact/checklist_gen.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_checklist_gen():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.checklist_gen")
    assert mod is not None

def test_generate_checklist_is_callable():
    """Function generate_checklist exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.checklist_gen")
    fn = getattr(mod, "generate_checklist", None)
    assert fn is not None, "'generate_checklist' not found in src.pact.checklist_gen"
    assert callable(fn)

def test_render_checklist_markdown_is_callable():
    """Function render_checklist_markdown exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.checklist_gen")
    fn = getattr(mod, "render_checklist_markdown", None)
    assert fn is not None, "'render_checklist_markdown' not found in src.pact.checklist_gen"
    assert callable(fn)
