"""Smoke tests for src/pact/backends/__init__.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_backends___init__():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.backends.__init__")
    assert mod is not None

def test_create_backend_is_callable():
    """Function create_backend exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.backends.__init__")
    fn = getattr(mod, "create_backend", None)
    assert fn is not None, "'create_backend' not found in src.pact.backends.__init__"
    assert callable(fn)
