"""Smoke tests for src/pact/human/linear.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_human_linear():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.human.linear")
    assert mod is not None

def test_sync_tree_to_linear_is_callable():
    """Function sync_tree_to_linear exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.human.linear")
    fn = getattr(mod, "sync_tree_to_linear", None)
    assert fn is not None, "'sync_tree_to_linear' not found in src.pact.human.linear"
    assert callable(fn)
