"""Smoke tests for src/pact/agents/shaper.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_agents_shaper():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.agents.shaper")
    assert mod is not None
