"""Smoke tests for src/pact/agents/trace_analyst.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_agents_trace_analyst():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.agents.trace_analyst")
    assert mod is not None

def test_analyze_trace_is_callable():
    """Function analyze_trace exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.agents.trace_analyst")
    fn = getattr(mod, "analyze_trace", None)
    assert fn is not None, "'analyze_trace' not found in src.pact.agents.trace_analyst"
    assert callable(fn)
