"""Smoke tests for src/pact/remediator.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_remediator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.remediator")
    assert mod is not None

def test_build_narrative_debrief_is_callable():
    """Function build_narrative_debrief exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.remediator")
    fn = getattr(mod, "build_narrative_debrief", None)
    assert fn is not None, "'build_narrative_debrief' not found in src.pact.remediator"
    assert callable(fn)

def test_generate_reproducer_test_is_callable():
    """Function generate_reproducer_test exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.remediator")
    fn = getattr(mod, "generate_reproducer_test", None)
    assert fn is not None, "'generate_reproducer_test' not found in src.pact.remediator"
    assert callable(fn)

def test_remediate_incident_is_callable():
    """Function remediate_incident exists and is callable."""
    import importlib
    mod = importlib.import_module("src.pact.remediator")
    fn = getattr(mod, "remediate_incident", None)
    assert fn is not None, "'remediate_incident' not found in src.pact.remediator"
    assert callable(fn)
