"""Smoke tests for src/pact/agents/base.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_pact_agents_base():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.pact.agents.base")
    assert mod is not None
