"""Smoke tests for src/pact/human/context.py (auto-generated by pact adopt)."""

import pytest

def test_import_pact_human_context():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("pact.human.context")
    assert mod is not None

def test_gather_context_is_callable():
    """Function gather_context exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.human.context")
    fn = getattr(mod, "gather_context", None)
    assert fn is not None, "'gather_context' not found in pact.human.context"
    assert callable(fn)

def test_check_for_human_response_is_callable():
    """Function check_for_human_response exists and is callable."""
    import importlib
    mod = importlib.import_module("pact.human.context")
    fn = getattr(mod, "check_for_human_response", None)
    assert fn is not None, "'check_for_human_response' not found in pact.human.context"
    assert callable(fn)
